### ISSUE TITLE
Add icons and menu items

### ISSUE THREAD

**Issue by ivanstegic** [ivanstegic/menu-bar-dns#5]
### Requirements

Pull requests should be made on the `develop` branch of this repo. Start with [release v0.0.1](https://github.com/ivanstegic/menu-bar-dns/releases/tag/v0.0.1) and consider that when the app starts, the following should be true:
1. When clicking on the menu bar icon, the app should no longer exit
2. Clicking on the menu bar icon should reveal a menu that is only as high as the number of items in it and as wide as the widest item. There should be a reasonable amount of padding around the items, as per Apple design guidelines. See the [Zoom menu screenshot](https://github.com/ivanstegic/menu-bar-dns/blob/develop/screenshots/zoom-menu.png) for a good example.
3. The menu should have 3 items, the last two should be separated from those above it by a grey line, see the [Zoom menu screenshot](https://github.com/ivanstegic/menu-bar-dns/blob/develop/screenshots/zoom-menu.png) for an example for the grey line.
4. The item above the grey line should read `Hello!`
4. The 2 items below the grey line should read `Help` and `Quit Menu Bar DNS`
5. Clicking on `Help` should open the URL `https://ivanstegic.com/menu-bar-dns/`
6. Clicking on `Quit Menu Bar DNS` should quit the application (exit)
7. All app icons should be the same SVG as used for the menu bar icon
8. The menu bar icon should be white in color when the screen background is dark, and the current color when the background is light. Current behavior is shown below

https://user-images.githubusercontent.com/509217/104105518-4313ff00-5274-11eb-9c72-f21d3ee9f948.mov

**Comment by munirahmed007** [comment]
Hi @ivanstegic 
to support the dark mode of screen, we must have a white version of the icon. Can you please provide me that? This way we don't need to handle it. Otherwise, I may have to handle the switch between white/dark programmatically which will need some effort.

**Comment by ivanstegic** [comment]
@munirahmed007 yes, of course! Here is the icon with a white fill. (I had to ZIP the file because the Github UI does not support SVG images for upload.)


[barcode-box-fill-white.svg.zip](https://github.com/ivanstegic/menu-bar-dns/files/5791608/barcode-box-fill-white.svg.zip)

**Comment by munirahmed007** [comment]
cool. Thanks.

**Comment by munirahmed007** [comment]
PR is ready:
https://github.com/ivanstegic/menu-bar-dns/pull/6

**Comment by ivanstegic** [comment]
@munirahmed007 please can you do another PR from `develop` as in the issue?

**Comment by munirahmed007** [comment]
@ivanstegic 
sure I changed the base in same PR. I hope that serves the purpose.

**Comment by ivanstegic** [comment]
@munirahmed007 i am afraid that the icon colors are not changing as i specified, see the video. You will notice that all the other icons change, except for Adobe's and Menu Bar DNS



https://user-images.githubusercontent.com/509217/104115104-47223a00-52d1-11eb-87da-79e80759963c.mov

**Comment by ivanstegic** [comment]
Also, the compiled .app file does not contain the App icons as specified

<img width="595" alt="Screen Shot 2021-01-09 at 11 22 29 PM" src="https://user-images.githubusercontent.com/509217/104115144-97010100-52d1-11eb-9576-f1a9ba38f568.png">

**Comment by munirahmed007** [comment]
HI @ivanstegic 

the dark/light behaviour should be fixed.
for app Icon, I will require icns fie.

**Comment by munirahmed007** [comment]
either i could be .icns file with multiple size or, you can provide me image file for each size.
sizes requires are
16x16
32x32
64x64
128x128
256x256
512x512
1024x1024

**Comment by ivanstegic** [comment]
Here you go!

[barcode-box-fill.zip](https://github.com/ivanstegic/menu-bar-dns/files/5793246/barcode-box-fill.zip)

**Comment by munirahmed007** [comment]
done.

**Comment by ivanstegic** [comment]
Great! Accepting the PR, thank you.
