### ISSUE TITLE
Enabling and disabling DNS servers

### ISSUE THREAD

**Issue by ivanstegic** [ivanstegic/menu-bar-dns#9]
### Requirements

1. It is possible to "enable" and "disable" DNS servers for the computer.
2. Names of network connections are no longer grey, rather they look like enabled menu items and are still bold
3. IP addresses of DNS servers are only greyed out as in v0.0.3 if they are associated with a network connection, but not currently being used by that connection as a DNS server. Call this an "inactive DNS server item"
4. IP addresses of DNS servers that are currently in use by a network connection are enabled, the same color as the "Help" menu item, and have a check mark in front of them. Call this an "active DNS server item"
5. Hovering on an inactive DNS server item highlights the item. Clicking on it puts a check mark in front of the item, item remains highlighted. This enables the item. It is now an active DNS server item.
6. Hovering on an active DNS server item greys out the item, making it look inactive. Clicking on it removes the check mark in front of the item, item remains greyed out. This disables the item. It is now an inactive DNS server item. When hovering over the item initially, the check mark should also be greyed out, the image below does not show a checkmark. Let's try it with the check mark first.
7. The app keeps track of all DNS server items and the connection that they are associated with. 
8. The app updates the corresponding network connection with the IP address of the active DNS server item. There can be more than one active DNS server per connection.
9. With this release, the app starts with the DNS IP addresses that are setup on each connection. There is no way to add or remove IP addresses to each connection.

Please see the wireframes below for more information.

![v0 0 3 to v0 0 4](https://user-images.githubusercontent.com/509217/104459285-27f60780-5572-11eb-8f44-f20d0da0978e.png)

**Comment by munirahmed007** [comment]
Hi @ivanstegic 

I want to understand more about inactive DNS servers:

In System Configuration for the network, we have two types of  DNS entries

1. DNS Server IPs which are inside the `State` Dictionary key. These are the IPs that are automatically assigned by the router when WiFi/ethernet adapter connects with it. They appear as greyed out in network preferences as shown in this attached image:

<img width="338" alt="Screenshot 2021-01-13 at 10 21 52 PM" src="https://user-images.githubusercontent.com/2619707/104486579-c4112480-55ed-11eb-8d1e-f438a3ad3b7a.png">

Such IPs are active and used by system unless user adds manual IPs for DNS. In that case, above IPs are no longer being used. That's what you call 'inactive` DNS IPs?

in V0.0.3, whenever the user clicks on the menubar, we fetch DNS IPs from network configuration. Now, in v0.0.4, we want to inactivate/activate IPs thru menu items which, in turn, will also change network configuration. Deactivating an IP will mean we will remove those IPs from the manual list of DNS server. I guess we still want to keep deactivated IPs in our list, right?

**Comment by ivanstegic** [comment]
Closing this, won't do. Other issues to follow.
